baseURL = "https://smasetty.github.io"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Sharat Masetty"
theme = "beautifulhugo"
copyright = ""
canonifyurls = true
publishdir = "smasetty.github.io"

[Author]
    name = "Sharat Masetty"
    email = "sharat_masetty@yahoo.com"
    twitter = "smasetty"
    github = "smasetty"

[Params]
    homeTitle = "Personal blog"
    subTitle = "Everything under the sun :-) | Unlearn-Relearn-Repeat"
    comments = true
    mainSections = ["post","posts"]
    logo = "img/avatar-icon.png" # Expecting square dimensions
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    readingTime = true
    wordCount = true
    showRelatedPosts = true

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
