baseURL = "smasetty.github.io"
languageCode = "en-us"
title = "Sharat Masetty"
theme = "beautifulhugo"
copyright = ""
publishdir = "smasetty.github.io"

[Author]
    name = "Sharat Masetty"
    email = "sharat_masetty@yahoo.com"
    twitter = "smasetty"
    github = "smasetty"

[params]
    homeTitle = "Personal blog"
    subTitle = "Everything under the sun :-) | Unlearn-Relearn-Repeat"
    comments = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
